# Generated by Django 5.2.1 on 2025-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('books', 'Books'), ('other', 'Other')], max_length=100),
        ),
    ]
